/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hardwareshop.view;


import hardwareshop.controller.CustomerManagementController;
import hardwareshop.model.Customer;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sandhanu
 */
public class CustomerManagement extends javax.swing.JFrame {
   private DefaultTableModel tableModel;
    /**
     * Creates new form InventoryManagement
     */
    public CustomerManagement() {
        initComponents();
         tableModel = new DefaultTableModel(new Object[]{"Customer ID","Name", "ContactInfo"}, 0);
        jTable1.setModel(tableModel);
        loadItems();
    }
     private void loadItems() {
        tableModel.setRowCount(0);

        for (Customer List : CustomerManagementController.getCustomer()) {
            tableModel.addRow(new Object[]{List.getCustomerID(),List.getName(), List.getContactInfo()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearch = new javax.swing.JLabel();
        TxtSearchID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtName = new javax.swing.JTextField();
        TxtContactInfo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSearch.setText("Search");

        TxtSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchIDActionPerformed(evt);
            }
        });
        TxtSearchID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSearchIDKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "ContactInfo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TxtContactInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContactInfoActionPerformed(evt);
            }
        });

        jLabel2.setText("Name :");

        jLabel1.setText("Contact Info :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Inventory Management");

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblSearch)
                        .addGap(28, 28, 28)
                        .addComponent(TxtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(197, 197, 197)
                            .addComponent(jButton1)
                            .addGap(40, 40, 40)
                            .addComponent(jButton2)
                            .addGap(35, 35, 35)
                            .addComponent(jButton3)
                            .addGap(0, 91, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtContactInfo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(TxtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtSearchIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSearchIDKeyReleased
//       int valueOf = Integer.parseInt("0"+TxtSearchID.getText());
       
        Customer searchCustomer = CustomerManagementController.searchCustomer(Integer.parseInt("0"+TxtSearchID.getText()) );
        if (!(null == searchCustomer)) {
            TxtName.setText(searchCustomer.getName());
            TxtContactInfo.setText(searchCustomer.getContactInfo());
           
       

        } else {
            clearTxt();
        }
    }//GEN-LAST:event_TxtSearchIDKeyReleased

    private void TxtContactInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContactInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContactInfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Customer customer = new Customer(Integer.valueOf(TxtSearchID.getText()),TxtName.getText(), TxtContactInfo.getText());
        boolean isaddedItem = CustomerManagementController.addCustomer(customer);
        
        if (isaddedItem) {
            JOptionPane.showMessageDialog(null, "Added!");
        } else {
            JOptionPane.showMessageDialog(null, "Not Added!");
        }
        loadItems();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean updateItem = CustomerManagementController.updateCustomer(
                new Customer(
                       Integer.valueOf(TxtSearchID.getText()),
                        TxtName.getText(),
                        TxtContactInfo.getText()
                      
                        
                ));
 
        if (updateItem) {
            JOptionPane.showMessageDialog(null, "Updated!");
        } else {
            JOptionPane.showMessageDialog(null, "Not Updated!");
        }
        loadItems();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean removecustomer = CustomerManagementController.removeCustomer(TxtSearchID.getText());
        if (removecustomer) {
            JOptionPane.showMessageDialog(null, "Removed!");
        } else {
            JOptionPane.showMessageDialog(null, "Not Removed!");
        }
         clearTxt();
        loadItems();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSearchIDActionPerformed
 public void clearTxt() {
        TxtName.setText(null);
          TxtContactInfo.setText(null);
      
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtContactInfo;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtSearchID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSearch;
    // End of variables declaration//GEN-END:variables
}
