/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hardwareshop.view;

import hardwareshop.controller.SalesManagementController;
import hardwareshop.model.Sales;
import java.util.Objects;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sandhanu
 */
public class SalesReports extends javax.swing.JFrame {

    private DefaultTableModel tableModel;

    /**
     * Creates new form SalesReports
     */
    public SalesReports() {
        initComponents();
        tableModel = new DefaultTableModel(new Object[]{"Sales ID", "Item ID", "Customer ID", "Quantity", "Total"}, 0);
        jTable1.setModel(tableModel);
        loadItems();
    }

    private void loadItems() {
        tableModel.setRowCount(0);

//        for (Sales List : SalesManagementController.getSales()) {
//            
//            tableModel.addRow(new Object[]{List.getSalesID(), List.getItemID(), List.getCustomerID(), List.getQuantity(), List.getTotalPrice()});
//        }
    }

    public void getTable() {
        Double salesTot = 0d;
        String[] dateComponentsStartInput = StartDate.getText().split("-");
        Integer yearStartInput = Integer.valueOf(dateComponentsStartInput[0]);
        Integer monthStartInput = Integer.valueOf(dateComponentsStartInput[1]);
        Integer dayStartInput = Integer.valueOf(dateComponentsStartInput[2]);

        String[] dateComponentsEndInput = EndDate.getText().split("-");
        Integer yearEndInput = Integer.valueOf(dateComponentsEndInput[0]);
        Integer monthEndInput = Integer.valueOf(dateComponentsEndInput[1]);
        Integer dayEndInput = Integer.valueOf(dateComponentsEndInput[2]);

        for (Sales List : SalesManagementController.getSales()) {
            String dateTime = List.getDate();
            String[] splitDateTime = dateTime.split(" ");
            String date = splitDateTime[0];

            String[] dateComponents = date.split("-");
            Integer year = Integer.valueOf(dateComponents[0]);
            Integer month = Integer.valueOf(dateComponents[1]);
            Integer day = Integer.valueOf(dateComponents[2]);

            if (yearEndInput > year && year > yearStartInput) {
                //salesTot += List.getTotalPrice();
tableModel.addRow(new Object[]{List.getSalesID(), List.getItemID(), List.getCustomerID(), List.getQuantity(), List.getTotalPrice()});
            } else if (Objects.equals(yearStartInput, year)) {
                System.out.println("K");
                if (month > monthStartInput) {
                    System.out.println("Kp");
                    tableModel.addRow(new Object[]{List.getSalesID(), List.getItemID(), List.getCustomerID(), List.getQuantity(), List.getTotalPrice()});
                    //salesTot += List.getTotalPrice();
                } else if (Objects.equals(monthStartInput, month)) {
                    if (day >= dayStartInput) {
tableModel.addRow(new Object[]{List.getSalesID(), List.getItemID(), List.getCustomerID(), List.getQuantity(), List.getTotalPrice()});
                        //salesTot += List.getTotalPrice();
                    }
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartDate = new javax.swing.JTextField();
        EndDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        StartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDateActionPerformed(evt);
            }
        });

        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sales ID", "Item ID", "Customer ID", "Quantity", "Total"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setText("Start Date(YYYY-MM-DD)");

        jLabel2.setText("End Date(YYYY-MM-DD)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sales Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndDate;
    private javax.swing.JTextField StartDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
