package hardwareshop.view;

import hardwareshop.controller.SalesManagementController;
import hardwareshop.model.Customer;
import hardwareshop.model.Item;
import hardwareshop.model.Sales;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sandhanu
 */
public class SalesManagement extends javax.swing.JFrame {

    private DefaultTableModel tableModel;

    /**
     * Creates new form SalesManagement
     */
    public SalesManagement() {
        initComponents();
        tableModel = new DefaultTableModel(new Object[]{"Sales ID", "Item ID", "Customer ID", "Quantity", "Total"}, 0);
        jTable1.setModel(tableModel);
        loadItems();
    }

    private void loadItems() {
        tableModel.setRowCount(0);

        for (Sales List : SalesManagementController.getSales()) {
            tableModel.addRow(new Object[]{List.getSalesID(), List.getItemID(), List.getCustomerID(), List.getQuantity(), List.getTotalPrice()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StartDate = new javax.swing.JTextField();
        EndDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        lblSalesPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSelectItem = new javax.swing.JComboBox<>();
        jComboBoxSelectCustomer = new javax.swing.JComboBox<>();
        TxtQtySales = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TxtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Sales Management");

        StartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDateActionPerformed(evt);
            }
        });

        jLabel2.setText("Start Date(YYYY-MM-DD)");

        jLabel3.setText("End Date(YYYY-MM-DD)");

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        lblSalesPrice.setText("0");

        jLabel4.setText("Total Sales:");

        jComboBoxSelectItem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxSelectItemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jComboBoxSelectCustomer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxSelectCustomerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        TxtQtySales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtQtySalesKeyReleased(evt);
            }
        });

        jButton1.setText("Record Sale");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TxtTotal.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sales ID", "Item ID", "Customer ID", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel5.setText("Select Items");

        jLabel6.setText("Select Customer");

        jLabel7.setText("Qty");

        jLabel8.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TxtQtySales, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxSelectItem, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(StartDate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFilter)
                            .addComponent(lblSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSelectItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtQtySales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDateActionPerformed

    private void jComboBoxSelectCustomerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxSelectCustomerAncestorAdded
        for (Customer List : SalesManagementController.getAllCustomers()) {
            jComboBoxSelectCustomer.addItem(List.getCustomerID() + "," + List.getName());
        }
    }//GEN-LAST:event_jComboBoxSelectCustomerAncestorAdded

    private void jComboBoxSelectItemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxSelectItemAncestorAdded
        for (Item List : SalesManagementController.getAllItems()) {
            jComboBoxSelectItem.addItem(List.getName() + "(ID :" + List.getItemID() + ")-Qty : " + List.getQuantity() + ",Price:$" + List.getPrice());
        }
    }//GEN-LAST:event_jComboBoxSelectItemAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Integer qty = Integer.valueOf("0" + TxtQtySales.getText());
        Item getItem = SalesManagementController.getAllItems().get(jComboBoxSelectItem.getSelectedIndex());
        Customer getCustomer = SalesManagementController.getAllCustomers().get(jComboBoxSelectCustomer.getSelectedIndex());
        Double price = getItem.getPrice();

        TxtTotal.setText((price * qty) + "");
        Sales sales = new Sales(getItem.getItemID(), getCustomer.getCustomerID(), qty, price);
        boolean isaddedItem = SalesManagementController.addItem(sales);

        if (isaddedItem) {
            JOptionPane.showMessageDialog(null, "Added!");
        } else {
            JOptionPane.showMessageDialog(null, "Not Added!");
        }
        loadItems();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtQtySalesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtQtySalesKeyReleased
        Integer qty = Integer.valueOf("0" + TxtQtySales.getText());
        Item getItem = SalesManagementController.getAllItems().get(jComboBoxSelectItem.getSelectedIndex());
        Double price = getItem.getPrice();
        TxtTotal.setText((price * qty) + "");
    }//GEN-LAST:event_TxtQtySalesKeyReleased

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        //ArrayList<Sales> sales = SalesManagementController.getSales();
        Double salesTot = 0d;
        String[] dateComponentsStartInput = StartDate.getText().split("-");
        Integer yearStartInput = Integer.valueOf(dateComponentsStartInput[0]);
        Integer monthStartInput = Integer.valueOf(dateComponentsStartInput[1]);
        Integer dayStartInput = Integer.valueOf(dateComponentsStartInput[2]);

        String[] dateComponentsEndInput = EndDate.getText().split("-");
        Integer yearEndInput = Integer.valueOf(dateComponentsEndInput[0]);
        Integer monthEndInput = Integer.valueOf(dateComponentsEndInput[1]);
        Integer dayEndInput = Integer.valueOf(dateComponentsEndInput[2]);
        for (Sales List : SalesManagementController.getSales()) {
            String dateTime = List.getDate();
            String[] splitDateTime = dateTime.split(" ");
            String date = splitDateTime[0];

            String[] dateComponents = date.split("-");
            Integer year = Integer.valueOf(dateComponents[0]);
            Integer month = Integer.valueOf(dateComponents[1]);
            Integer day = Integer.valueOf(dateComponents[2]);

            if (yearEndInput > year && year > yearStartInput) {
                salesTot += List.getTotalPrice();

            } else if (Objects.equals(yearStartInput, year)) {
                System.out.println("K");
                if ( month > monthStartInput) {
                    System.out.println("Kp");
                    salesTot += List.getTotalPrice();
                } else if (Objects.equals(monthStartInput, month)) {
                    if ( day >= dayStartInput) {

                        salesTot += List.getTotalPrice();
                    }
                }
            }

        }
        lblSalesPrice.setText(Math.round(salesTot) + "");
    }//GEN-LAST:event_btnFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndDate;
    private javax.swing.JTextField StartDate;
    private javax.swing.JTextField TxtQtySales;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSelectCustomer;
    private javax.swing.JComboBox<String> jComboBoxSelectItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSalesPrice;
    // End of variables declaration//GEN-END:variables
}
